name: Deploy to Production

on:
  push:
    branches:
      - main # replace with the branch you want to deploy
    workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies and build Strapi
      run: |
        cd strapi
        npm ci
        npm run build

    - name: List files in strapi directory
      run: |
        cd strapi
        ls -la

    - name: Deploy Strapi to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "strapi/" # change to your Strapi folder
        target: "/var/www/within-reason/"
        debug: true

    - name: Install PM2 and start/restart Strapi
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          which node
          sudo nvm use 16
          sudo npm install -g pm2
          cd /var/www/within-reason/strapi/
          sudo pm2 startOrRestart ecosystem.config.js # replace with your PM2 config file

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    env:
      VITE_BUILD_ENV: 'production' 
      VITE_BASE_URL_PROD: ${{ secrets.VITE_BASE_URL_PROD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # set the Node.js version you're using

    - name: Install dependencies and build Vue app
      run: |
        cd app # change to your Vue folder
        npm ci
        npm run build

    - name: Deploy Vue app to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "app/dist/" # change to your Vue dist folder
        target: "/var/www/within-reason"
